Check pipeline shutdown status while waiting for valid connection or while issuing a bulk to ES
logstash-plugins/logstash-output-elasticsearch pull request #1119
Opened 2023-03-08 15:30 UTC by andsel

Fix https://github.com/elastic/logstash/issues/14739
Superseed #1107
Superseed #1117
Relates https://github.com/elastic/logstash/pull/14940

2023-03-23 07:52 UTC, andsel commented
The tests for version `8.x` are green because the selected version results to be `8.7.0-SNAPSHOT`.
The testing against `8.8.0-SNAPSHOT` will happen after the `8.7.0` release, when selected [snapshot version change](https://github.com/elastic/logstash/blob/56e626afc55cc9360c0d8c8e1c63e743900ea0a0/ci/logstash_releases.json#L10).

2023-03-31 11:27 UTC, jsvd requested changes
I tested a few scenarios:
A) Writing to ES when the API key is revoked and the Pipeline is updated with new API Key: pipeline restarts correctly ✅ 
B) Writing to ES when ES goes down, binds to a different port, Pipeline is updated with new port: the pipeline never terminates 🛑 

B) seems to fail as the ressureccionist thread never terminates, likely due to https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/main/lib/logstash/outputs/elasticsearch/http_client/pool.rb#L129C11-L146

2023-04-03 13:29 UTC, andsel commented
The `stop` method is invoked as a notification after all the pipeline workers has terminated. The  `@stopping` at 
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/a0b4832bd4d4e045cdc2c485e79c5949379c96b3/lib/logstash/outputs/elasticsearch/http_client/pool.rb#L91
is invoked _after_ the plugin has terminated his `#multi_process` from the LS's pipeline during [shutdown_workers](url) execution.

A solution to exit the resurrectionist loop would be to propagate the `shutdown_requested ` down to the ES pool so that the `@stopping` could be flipped both during `#close` and also when shutdown is requested.

2023-04-04 08:00 UTC, andsel commented
With commit 5e57c3ab7854fbbd7a8f2d708b1b09e9e343bb17 was introduced the abort of a batch in case no connections are available in the pool and the pipeline is shutting down.

2023-04-04 10:39 UTC, jsvd approved these changes
LGTM, tested manually a few scenarios, ran the unit tests without the necessary patches, everything is working as expected.  :shipit:

2023-04-04 13:38 UTC, merged