Feature/use integration metadata to create es actions
logstash-plugins/logstash-output-elasticsearch pull request #1155
Opened 2023-10-25 15:59 UTC by andsel

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

2023-11-03 17:19 UTC, yaauie reviewed
It looks like we have a mix of precedences.

The `pipeline` and `id` seem to work as-specified with explicit plugin configuration always overriding implicit discovery of the event, but `index` is reversed and allows implicitly-discovered values to override explicit plugin configuration.

There are also some gaps in the spec coverage, which should cover all of:

 - `index`:
   - when plugin's `index` is specified
     - when event metadata contains `index`
       - plugin's `index` is used
     - when event metadata does not contain `index`
       - plugin's `index` is used
   - when plugin's `index` is NOT specified
     - when event metadata contains `index`
       - event metadata `index` is used
     - when event metadata does not contain `index`
       - plugin's _default_ `index` mechanism is used (including data streams variants)
 - `id`: 
   - when plugin's `document_id` is specified
     - when event metadata contains `id`
       - plugin's `document_id` is used
     - when event metadata does not contain `id`
       - plugin's `document_id` is used
   - when plugin's `document_id` is NOT specified
     - when event metadata contains `id`
       - event metadata `id` is used
     - when event metadata does not contain `id`
       - plugin's _default_ `id` mechanism is used (action tuple _excludes_ an `id`)
 - `pipeline`:
   - when plugin's `pipeline` is specified
     - when event metadata contains `pipeline`
       - plugin's `pipeline` is used
     - when event metadata does not contain `pipeline`
       - plugin's `pipeline` is used
   - when plugin's `pipeline` is NOT specified
     - when event metadata contains `pipeline`
       - event metadata `pipeline` is used
     - when event metadata does not contain `pipeline`
       - plugin's _default_ `pipeline` mechanism is used (action tuple _excludes_ a `pipeline`)

2023-11-03 17:19 UTC, yaauie commented on spec/unit/outputs/elasticsearch_spec.rb
> +      context "when there isn't any index setting specified and the event contains an integration metadata index" do
From line 192, which appears to be the outer context group for this example context, the `options` includes an `index` directive.

When an `index` is explicitly given in the plugin configuration, it _must_ supercede the metadata.

As-specified, explicit configuration _always_ takes precedence over implicit discovery.

2023-11-06 18:02 UTC, andsel commented
Hi @yaauie, thank's a lot for your review. I've integrated your suggestion and the PR is ready for a second round of review 🙏

2023-11-07 18:00 UTC, yaauie requested changes
The implementation looks clean and the spec coverage makes the behaviour clear.

We need a changelog entry and a version bump, and should consider whether to document this in the user-facing docs.

Suggestion for the changelog:

> ~~~ markdown
>  - Adds support for propagating event processing metadata when this output is downstream of an Elastic Integration Filter and configured _without_ explicit `index`, `document_id`, or `pipeline` directives [#1155](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1155)
> ~~~

I am not strongly opposed to including a user-facing blurb in the docs, but I don't think it adds much value and could lead to abuse.

2023-11-09 00:28 UTC, yaauie approved these changes
LGTM :+1:

2023-11-10 09:14 UTC, merged